### ISSUE TITLE
Advice for improving usability

### ISSUE THREAD

**Issue by berkesenturk** [nazliander/scrape-nr-of-deaths-istanbul#5]
## Description

As a beginner docker user maybe I get it wrong, please show the right way if I did but it seems your scraping functions are relying on files to get the csv of dates for example. My question is, Is it possible to get inputs by end-users for example from cli?

And I get ``` FileNotFoundError: [Errno 2] No such file or directory: '/app/__logger/selenium_stats.log'``` error when I build the image. Can you please describe what it is selenium_stats.log used for in Readme or in comments?

On the other hand, it is a very good example for those learning to use Selenium with Docker. Thank you for your time.

**Comment by nazliander** [comment]
Thanks a lot, @berkesenturk for pointing this out. The Docker must be working now with the logger, it was requiring to output the logs to a file on a non-existing path. The PR that is linked has a `mkdir` command, this must be solving the issue you stated.

Apart from this, unfortunately, the main page to be scraped started using captchas. Thus the code is outdated, and we will be seeing `no such element` error.

Please consider this project as an example of using Selenium in a Docker container to scrape basic websites.
