### ISSUE TITLE
apt-key: not found

### ISSUE THREAD

**Issue by bhattraideb** [nazliander/scrape-nr-of-deaths-istanbul#7]
I am getting this error:
```
 => ERROR [ 4/11] RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -                                                               0.7s
------
 > [ 4/11] RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -:
#7 0.315 /bin/sh: apt-key: not found
------
executor failed running [/bin/sh -c wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -]: exit code: 127
ERROR: Service 'app' failed to build
```

**Comment by nazliander** [comment]
Unfortunately, I was not able to reproduce this error when I build the image from scratch.

Are you using the same base image and the Dockerfile? (`python:3.8`)

**Comment by bhattraideb** [comment]
I am using python:3.8-alpine version.

**Comment by nazliander** [comment]
@bhattraideb In the Alpine Linux there is no `apt-get` or `apt-key`. Thus the given solution would not work with an Alpine base image. You can try to use `python:3.8` base image as the example does.

If the Alpine Linux is necessary for your needs, there is a cool project in the following repository: https://github.com/Zenika/alpine-chrome

Hope it was helpful.

**Comment by bhattraideb** [comment]
This solved the issue. Thanks @nazliander .
